export const mockArticles = [
  {
    slug: 'how-to-train-your-dragon',
    title: 'How to train your dragon',
    description: 'Ever wonder how?',
    body: 'It takes a Jacobian',
    tags: ['dragons', 'training'],
    createdAt: '2025-05-04T09:42:00Z',
    favoritesCount: 42,
    author: { username: 'jake', image: 'https://api.realworld.io/images/smiley-cyrus.jpg' },
  },
  {
    slug: 'article-2',
    title: 'Статья 2',
    description: 'Описание',
    body: 'Текст статьи',
    tags: ['tag2'],
    createdAt: '2025-05-03T09:42:00Z',
    favoritesCount: 12,
    author: { username: 'john', image: 'https://via.placeholder.com/50' },
  },
  {
    slug: 'article-3',
    title: 'Статья 3',
    description: 'Описание',
    body: 'Текст статьи',
    tags: ['tag3'],
    createdAt: '2025-05-02T09:42:00Z',
    favoritesCount: 13,
    author: { username: 'jane', image: 'https://via.placeholder.com/50' },
  },
  {
    slug: 'article-4',
    title: 'Статья 4',
    description: 'Описание',
    body: 'Текст статьи',
    tags: ['tag4'],
    createdAt: '2025-05-01T09:42:00Z',
    favoritesCount: 5,
    author: { username: 'alice', image: 'https://via.placeholder.com/50' },
  },
]
